"""Init file for the prompts package."""

from .prompts import (
    AUGMENTED_PROMPT,
    BASE_PROMPT,
    BUSINESS_UNIT_PROMPT,
    CATEGORY_PROMPT,
    DEFAULT_INSTRUCTION,
    FOLLOW_UP_PROMPT,
    TEMPLATE,)


from .risk_prompt import (
    RISK_MATRIX_ALL_RISKS_PROMPT2,
    USER_QUERY_RISKS,
    ADDITIONAL_RISKS,
    RISKS_SUMMARY,
    RISK_MATRIX_CATEGORY,
    RISK_MITIGATION_PROMPT,
    TEMPLATE,
    TOPIC_CHECKER,
)

__all__ = [
    "BASE_PROMPT",
    "AUGMENTED_PROMPT",
    "BUSINESS_UNIT_PROMPT",
    "CATEGORY_PROMPT",
    "DEFAULT_INSTRUCTION",
    "FOLLOW_UP_PROMPT",
    "TEMPLATE",
    ##risk prompts
    # "RISK_MATRIX_SPC_RISK_PROMPT",
    # "RISK_MATRIX_ALL_RISKS_PROMPT",
    # "RISK_MATRIX_PROMPT",
    "RISK_MATRIX_ALL_RISKS_PROMPT2",
    "RISK_MITIGATION_PROMPT",
    "USER_QUERY_RISKS",
    "ADDITIONAL_RISKS",
    "RISKS_SUMMARY",
    "RISK_MATRIX_CATEGORY"
]
