"""Init file for the prompts package."""

from .prompts import (
    AUGMENTED_PROMPT,
    BASE_PROMPT,
    BUSINESS_UNIT_PROMPT,
    CATEGORY_PROMPT,
    DEFAULT_INSTRUCTION,
    FOLLOW_UP_PROMPT,
    RISK_MATRIX_ALL_RISKS_PROMPT,
    RISK_MATRIX_PROMPT,
    RISK_MATRIX_SPC_RISK_PROMPT,
    RISK_MITIGATION_PROMPT,
    TEMPLATE,
    TOPIC_CHECKER,
)

__all__ = [
    "BASE_PROMPT",
    "AUGMENTED_PROMPT",
    "BUSINESS_UNIT_PROMPT",
    "CATEGORY_PROMPT",
    "DEFAULT_INSTRUCTION",
    "FOLLOW_UP_PROMPT",
    "RISK_MATRIX_SPC_RISK_PROMPT",
    "RISK_MATRIX_ALL_RISKS_PROMPT",
    "RISK_MATRIX_PROMPT",
    "TEMPLATE",
    "TOPIC_CHECKER",
    "RISK_MITIGATION_PROMPT",
]
